### ISSUE TITLE
txsummaries sometimes showing absurd fees after shield all cli call (probably integer underflow?)

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingolib#484]
This may be related to some value still showing up in the sapling pool after being migrated to orchard via do_shield (making the balance show as incorrect)

**Comment by juanky201271** [comment]
the same case here: https://github.com/zingolabs/zingolib/issues/483 really similar.

**Comment by zancas** [comment]
If you have a PR for this, can you link to it?

**Comment by zancas** [comment]
@AloeareV how's this bug progressing?

**Comment by zancas** [comment]
What we ( @juanky201271 and I ) to know is..  is this a bug in `txsummaries`?

If yes, then we need to fix it before we can deprecate `do_list_transactions`.

**Comment by juanky201271** [comment]
@zancas 
I don't see this astronomic fee for a while... I have to say that maybe this is fixed.

**Comment by zancas** [comment]
Since this is evidently (at least) intermittent (if not fixed), lets move it out of the milestone.

**Comment by juanky201271** [comment]
This is definitely fixed. closing...
