### ISSUE TITLE
Confirmed or unconfirmed, a Zingo dilemma.

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingolib#612]
I am using Zingo-Mobile which uses zingolib mob-release-1.3.0-169... and when making a transaction it shows as confirmed, but when checking from the browser, the transaction has no confirmations.

![Screenshot_20231020-104939.jpg](https://github.com/zingolabs/zingolib/assets/37910384/f67185e0-5c9d-4c8c-aa93-158bb24ebe76)

![Screenshot_20231020-104607.jpg](https://github.com/zingolabs/zingolib/assets/37910384/54a1ee15-3969-4961-848f-df8a30be453e)

This behavior is not the expected behavior and is not favorable for the user, showing that the transaction was confirmed when it really is not, will generate confusion in the user, especially at the moment he tries to make another transaction and the wallet tells him that he has no balance available and that a transaction is still being confirmed.

![Screenshot_20231020-105417.jpg](https://github.com/zingolabs/zingolib/assets/37910384/fa60fc3f-d87d-42dd-9c47-1dbe30cc493d)

![Screenshot_20231020-103912.jpg](https://github.com/zingolabs/zingolib/assets/37910384/892eaa5e-ad3c-4b32-ab50-c406e0a8af1c)

I will keep an eye out for retesting when they have fixed this problem. 🦓🍃

**Comment by juanky201271** [comment]
This APK is using `summaries` and we need a field like `unconfirmed` of `list` in `summaries`... or some other mechanism to know if the tx is mined or not.

**Comment by fluidvanadium** [comment]
this lines up with bugs im seeing in zingolib. some has to do with unconfirmed

others, the outrageous fees, is due to duplicate metadata

**Comment by zancas** [comment]
> this lines up with bugs im seeing in zingolib. some has to do with unconfirmed
> 
> others, the outrageous fees, is due to duplicate metadata

OK, can you add `unconfirmed` to `ValueTransfers`?

**Comment by zancas** [comment]
> I am using Zingo-Mobile which uses zingolib mob-release-1.3.0-169... and when making a transaction it shows as confirmed, but when checking from the browser, the transaction has no confirmations.
> 
> ![Screenshot_20231020-104939.jpg](https://user-images.githubusercontent.com/37910384/276976307-f67185e0-5c9d-4c8c-aa93-158bb24ebe76.jpg)
> 
> ![Screenshot_20231020-104607.jpg](https://user-images.githubusercontent.com/37910384/276976475-54a1ee15-3969-4961-848f-df8a30be453e.jpg)
> 
> This behavior is not the expected behavior and is not favorable for the user, showing that the transaction was confirmed when it really is not, will generate confusion in the user, especially at the moment he tries to make another transaction and the wallet tells him that he has no balance available and that a transaction is still being confirmed.
> 
> ![Screenshot_20231020-105417.jpg](https://user-images.githubusercontent.com/37910384/276976552-fa60fc3f-d87d-42dd-9c47-1dbe30cc493d.jpg)
> 
> ![Screenshot_20231020-103912.jpg](https://user-images.githubusercontent.com/37910384/276976794-892eaa5e-ad3c-4b32-ab50-c406e0a8af1c.jpg)
> 
> I will keep an eye out for retesting when they have fixed this problem. 🦓🍃

We have a fix for this, for transparent, in dev that we are currently testing.   Is this bug specific to transparent?  If it's more general than transparent then @Oscar-Pepper will need to fix that ASAP.

**Comment by zancas** [comment]
> This APK is using `summaries` and we need a field like `unconfirmed` of `list` in `summaries`... or some other mechanism to know if the tx is mined or not.

I asked @fluidvanadium to add `unconfirmed` to `ValueTransfer`.

**Comment by juanky201271** [comment]
I believe this issue is already fixed, I'm going to send to @Edicksonjga a new APK to test this... ASAP

**Comment by zancas** [comment]
Can we get specific block heights?   I believe that the confirmation process is correct, and we're seeing a difference reorg buffer lengths, and hence reporting.

**Comment by Edicksonjga** [comment]
The problem persists in the latest tests, Zingo Beta:

![Screenshot_20231101-115036.jpg](https://github.com/zingolabs/zingolib/assets/37910384/c298e632-25fe-47c0-9f11-390b005495aa)

@zancas @juanky201271
